name: Update Profile Stats
on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight UTC
  workflow_dispatch: # Allows manual runs

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      # Update GitHub Stats
      - name: Update GitHub Readme Stats
        uses: anuraghazra/github-readme-stats@latest
        with:
          username: brosq6168

  update-wakatime:
    runs-on: ubuntu-latest
    steps:
      # Update WakaTime Stats
      - name: Update WakaTime Readme Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_LANGUAGES: "true"
          SHOW_OS: "false"
