name: Update GitHub Stats
on:
  schedule:
    # Runs every day at 00:00 UTC (midnight)
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Update GitHub Stats
        uses: anuraghazra/github-readme-stats@latest
        with:
          username: brosq6168 # Replace with your username
          # Customize stats (optional)
          theme: dark
          hide_border: true
          show_icons: true
